name: HybridTestFramework

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: dipjyotimetia/hybridtestframework:2.0

    steps:
    - uses: actions/checkout@v2
    - uses: nanasess/setup-chromedriver@master
      with:
        # Optional: do not specify to match Chrome's version
        chromedriver-version: '83.0.4103.39'
    - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: End to End Test
      run: ./gradlew task e2e
