name: HybridTestFramework

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: dipjyotimetia/hybridtestframework:2.0

    steps:
    - uses: actions/checkout@v2
    - name: Install Google Chrome # Using shell script to install Google Chrome
      run: |
        chmod +x ./Driver/linux/InstallChrome.sh
         ./Driver/linux/InstallChrome.sh
    - name: End to End Test
      run: gradle task e2e
