name: HybridTestFramework

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install Google Chrome # Using shell script to install Google Chrome
      run: |
        chmod +x ./Driver/linux/InstallChrome.sh
         ./Driver/linux/InstallChrome.sh
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: End to End Test
      run: ./gradlew task e2e
